/* ======================================================================
   COMPLETE SUBJECT-SPECIFIC QUESTION BANKS
   All subjects, all levels, all meaningful questions and options
   ====================================================================== */

const SUBJECT_QUESTIONS = {
  English: {
    levelTitles: [
      "Grammar Basics", "Parts of Speech", "Tenses", "Sentence Structure", 
      "Punctuation Mastery", "Vocabulary Building", "Reading Comprehension", 
      "Writing Style", "Literary Devices", "Idioms and Phrases",
      "Homophones and Homonyms", "Prepositions", "Articles and Determiners", 
      "Subject-Verb Agreement", "Pronouns", "Adjectives and Adverbs", 
      "Complex Sentences", "Discourse and Coherence", "Essay Writing", 
      "Advanced Grammar and Communication"
    ],
    questions: {
      1: [
        { q: "Which word is a noun?", o: ["run", "happy", "book", "quickly"], a: 2 },
        { q: "What is the subject in 'The cat sat on the mat'?", o: ["mat", "sat", "cat", "on"], a: 2 },
        { q: "Choose the correct sentence:", o: ["She go to school.", "She goes to school.", "She going to school.", "She goed to school."], a: 1 },
        { q: "Which is an adjective?", o: ["laugh", "beautiful", "run", "quickly"], a: 1 },
        { q: "Identify the verb:", o: ["table", "red", "eat", "quickly"], a: 2 },
        { q: "What punctuation ends a question?", o: [".", "!", "?", ","], a: 2 },
        { q: "Choose the correct spelling:", o: ["occured", "occurred", "ocured", "occured"], a: 1 },
        { q: "Which word rhymes with 'cat'?", o: ["bat", "cake", "dog", "sit"], a: 0 },
        { q: "'There' means:", o: ["they are", "the place", "their possession", "through"], a: 1 },
        { q: "What is an adverb?", o: ["a person", "a place", "how an action is done", "a feeling"], a: 2 },
        { q: "Choose the correct plural:", o: ["childs", "child", "children", "childes"], a: 2 },
        { q: "Which sentence is correct?", o: ["I don't like apples.", "I doesn't like apples.", "I not like apples.", "I am not like apples."], a: 0 },
        { q: "What is a pronoun?", o: ["a name", "a word replacing a noun", "an action", "a description"], a: 1 },
        { q: "Choose: He/Him gave me a pen.", o: ["He", "Him", "Both are correct", "Neither is correct"], a: 0 },
        { q: "What does 'eloquent' mean?", o: ["shy", "talkative", "fluent and persuasive", "funny"], a: 2 }
      ],
      2: [
        { q: "Identify the prepositon:", o: ["beautiful", "under", "running", "happy"], a: 1 },
        { q: "Which uses correct capitalization?", o: ["john went to new york", "John went to New York", "JOHN WENT TO NEW YORK", "john Went To new york"], a: 1 },
        { q: "What is an article?", o: ["a piece of writing", "a tool", "a/an/the", "a preposition"], a: 2 },
        { q: "Choose correct: Between/Among the friends:", o: ["Between", "Among", "Both equally", "Neither"], a: 1 },
        { q: "Which is a conjunction?", o: ["very", "beautiful", "and", "slowly"], a: 2 },
        { q: "'Their' vs 'There': She put the book ____", o: ["their", "there", "they're", "thare"], a: 1 },
        { q: "What is alliteration?", o: ["rhyming", "repetition of sounds", "metaphor", "comparison"], a: 1 },
        { q: "Choose the compound word:", o: ["happy", "sunshine", "run", "beautiful"], a: 1 },
        { q: "Correct sentence:", o: ["She have a pen.", "She has a pen.", "She do have a pen.", "She having pen."], a: 1 },
        { q: "What is a synonym?", o: ["opposite word", "similar word", "new word", "rare word"], a: 1 },
        { q: "'Affect' vs 'Effect': The weather will ____ the game.", o: ["affect", "effect", "affectly", "effectly"], a: 0 },
        { q: "Identify the metaphor:", o: ["Life is like a journey", "Life is a journey", "Life is not a journey", "Journey of life"], a: 1 },
        { q: "Which word is an antonym of 'bright'?", o: ["dark", "light", "clear", "shiny"], a: 0 },
        { q: "What is a simile?", o: ["comparison using 'like' or 'as'", "repetition", "exaggeration", "pun"], a: 0 },
        { q: "Correct: 'Whom/Who' did you see?", o: ["Whom", "Who", "Both", "Neither"], a: 1 }
      ],
      3: [
        { q: "Which is past tense?", o: ["run", "runs", "ran", "running"], a: 2 },
        { q: "Future tense: I ____ go tomorrow.", o: ["am", "have", "will", "do"], a: 2 },
        { q: "Present continuous: She ____ reading.", o: ["is", "are", "be", "was"], a: 0 },
        { q: "Correct: I ____ finished.", o: ["have", "has", "had", "am"], a: 0 },
        { q: "Past perfect: She ____ left before I arrived.", o: ["have", "has", "had", "did"], a: 2 },
        { q: "Future perfect: By 2025, they ____ graduated.", o: ["will have", "have", "had", "will"], a: 0 },
        { q: "Present perfect: I ____ never seen snow.", o: ["have", "has", "had", "do"], a: 0 },
        { q: "Correct: He ____ working yesterday.", o: ["was", "is", "were", "be"], a: 0 },
        { q: "Which tense is 'will be going'?", o: ["future simple", "future continuous", "future perfect", "present continuous"], a: 1 },
        { q: "She ____ studied hard when she was younger.", o: ["use to", "used to", "uses to", "using to"], a: 1 },
        { q: "Past continuous: They ____ playing football.", o: ["was", "were", "are", "is"], a: 1 },
        { q: "Correct: If I ____ you, I would leave.", o: ["were", "was", "am", "be"], a: 0 },
        { q: "Conditional: I would have gone if I ____ known.", o: ["had", "have", "has", "would"], a: 0 },
        { q: "'I wish' uses what tense?", o: ["present", "past", "future", "perfect"], a: 1 },
        { q: "Correct: Since 1990, she ____ lived here.", o: ["has", "had", "have", "did"], a: 0 }
      ],
      4: [
        { q: "What is a phrase?", o: ["a complete sentence", "a group of related words", "a type of noun", "a verb"], a: 1 },
        { q: "Identify the dependent clause:", o: ["She walks to school", "When the sun sets", "He is happy", "They play games"], a: 1 },
        { q: "Which is a complex sentence?", o: ["She ran quickly.", "She ran and jumped.", "She ran while he watched.", "She ran very fast."], a: 2 },
        { q: "A compound sentence has:", o: ["one independent clause", "two independent clauses", "one dependent clause", "no verbs"], a: 1 },
        { q: "What joins independent clauses?", o: ["comma", "semicolon", "period and conjunction", "apostrophe"], a: 1 },
        { q: "Correct: 'Either/Neither' ____ is correct.", o: ["them", "one", "ones", "it"], a: 2 },
        { q: "Sentence fragment: 'Because the rain started.'", o: ["correct", "fragment", "run-on", "complete"], a: 1 },
        { q: "What is a run-on sentence?", o: ["too long", "two independent clauses without connection", "with no verb", "with no subject"], a: 1 },
        { q: "Correct use of 'may/can':", o: ["Can I help you?", "May I help you?", "Both are fine here", "Neither works"], a: 1 },
        { q: "What is a modifier?", o: ["a noun", "a word describing another word", "a verb", "a pronoun"], a: 1 },
        { q: "Misplaced modifier: 'Playing in the park, the ball went far.'", o: ["correct", "incorrect", "unclear", "perfect"], a: 1 },
        { q: "What is parallelism?", o: ["using same structure", "using different tenses", "using adjectives", "using adverbs"], a: 0 },
        { q: "Active vs passive: Choose active voice:", o: ["The book was read by her.", "She reads the book.", "The book is being read.", "Reading is being done."], a: 1 },
        { q: "What is a dangling modifier?", o: ["a misplaced modifier", "a correct modifier", "a conjunction", "a clause"], a: 0 },
        { q: "Correct: 'Hardly' is used with:", o: ["positive verbs", "negative constructions", "nouns", "adjectives"], a: 1 }
      ],
      5: [
        { q: "Colon introduces:", o: ["questions", "lists or explanations", "clauses", "dialogue only"], a: 1 },
        { q: "Semicolon connects:", o: ["dependent clauses", "two independent clauses", "only lists", "questions"], a: 1 },
        { q: "Apostrophe shows:", o: ["plural", "possession or contraction", "question", "emphasis"], a: 1 },
        { q: "Use dash for:", o: ["lists", "sudden breaks or emphasis", "questions", "abbreviations"], a: 1 },
        { q: "Comma splice fixes with:", o: ["adding word", "period or semicolon", "removing comma", "adding dash"], a: 1 },
        { q: "Quotation marks for:", o: ["direct speech/titles", "emphasis", "lists", "definitions"], a: 0 },
        { q: "'It's' vs 'Its': ____ cold and ____ raining.", o: ["It's, It's", "Its, its", "It's, its", "Its, It's"], a: 2 },
        { q: "Parentheses for:", o: ["main ideas", "additional information", "questions", "emphasis"], a: 1 },
        { q: "Ellipsis (...) indicates:", o: ["pause or omission", "emphasis", "question", "quotation"], a: 0 },
        { q: "When to use double negative:", o: ["always", "sometimes for emphasis", "never in standard English", "in questions"], a: 2 },
        { q: "Hyphen connects:", o: ["independent clauses", "compound words or prefixes", "sentences", "lists"], a: 1 },
        { q: "Exclamation point shows:", o: ["questions", "strong emotion", "statements", "lists"], a: 1 },
        { q: "Comma rules include:", o: ["between all adjectives", "before conjunctions with clauses", "after simple phrases", "before verbs"], a: 1 },
        { q: "When to use commas in addresses:", o: ["never", "after street only", "after city and state", "only before zip code"], a: 2 },
        { q: "Punctuation in dialogue:", o: ["comma before quote", "period before quote", "quote, comma, speaker", "no punctuation before quote"], a: 2 }
      ],
      6: [
        { q: "Synonym for 'happy':", o: ["sad", "joyful", "angry", "tired"], a: 1 },
        { q: "Synonym for 'large':", o: ["small", "big", "tiny", "huge"], a: 1 },
        { q: "Antonym of 'bright':", o: ["dark", "light", "shiny", "clear"], a: 0 },
        { q: "Synonym for 'quickly':", o: ["slowly", "rapidly", "lazily", "carefully"], a: 1 },
        { q: "Root 'bio' means:", o: ["water", "life", "earth", "fire"], a: 1 },
        { q: "Prefix 'un' means:", o: ["one", "not", "again", "before"], a: 1 },
        { q: "Suffix 'tion' indicates:", o: ["adjective", "noun (action)", "verb", "adverb"], a: 1 },
        { q: "Homophone for 'be':", o: ["bee", "sea", "see", "tea"], a: 0 },
        { q: "Homophone for 'pair':", o: ["pear", "pare", "pairs", "prayer"], a: 0 },
        { q: "What does 'benevolent' mean?:", o: ["mean", "kind", "angry", "lazy"], a: 1 },
        { q: "Antonym for 'generous':", o: ["stingy", "kind", "rich", "smart"], a: 0 },
        { q: "Root 'port' means:", o: ["break", "carry", "run", "build"], a: 1 },
        { q: "'Precede' means:", o: ["follow", "go before", "include", "prevent"], a: 1 },
        { q: "Prefix 'mis' means:", o: ["not", "bad/wrong", "before", "after"], a: 1 },
        { q: "Synonym for 'difficult':", o: ["easy", "hard", "simple", "smooth"], a: 1 }
      ],
      7: [
        { q: "Main idea of 'The Ant and the Grasshopper':", o: ["laziness", "hard work pays", "nature is cruel", "animals are wise"], a: 1 },
        { q: "What does 'inference' mean?:", o: ["stated fact", "educated guess from text", "summary", "theme"], a: 1 },
        { q: "Purpose of 'cause and effect':", o: ["describe", "explain why things happen", "tell story", "list facts"], a: 1 },
        { q: "Identify the sequence:", o: ["summary", "order of events", "main idea", "conclusion"], a: 1 },
        { q: "Supporting details:", o: ["main idea", "evidence for main idea", "conclusion", "introduction"], a: 1 },
        { q: "What is a summary?:", o: ["full text", "main points briefly", "conclusion only", "introduction"], a: 1 },
        { q: "Fact vs Opinion: 'Cats are animals.'", o: ["opinion", "fact", "both", "neither"], a: 1 },
        { q: "Point of view in third person:", o: ["uses 'I'", "uses 'you'", "uses 'he/she'", "direct address"], a: 2 },
        { q: "Foreshadowing shows:", o: ["past events", "hints of coming events", "transitions", "conclusions"], a: 1 },
        { q: "What is bias?:", o: ["balance", "prejudice or lean", "summary", "facts"], a: 1 },
        { q: "Author's tone can be:", o: ["words only", "mood conveyed through writing", "plot", "characters"], a: 1 },
        { q: "Context clues help:", o: ["count words", "guess unfamiliar words", "find themes", "make outlines"], a: 1 },
        { q: "Theme is:", o: ["plot", "main message/idea", "setting", "character"], a: 1 },
        { q: "What does 'explicit' mean?:", o: ["hidden", "clearly stated", "implied", "confusing"], a: 1 },
        { q: "Implicit information:", o: ["stated clearly", "suggested/implied", "obvious", "in title"], a: 1 }
      ],
      8: [
        { q: "Formal writing uses:", o: ["slang", "contractions", "sophisticated vocabulary", "jokes"], a: 2 },
        { q: "Tone in 'Help!' is:", o: ["calm", "urgent", "happy", "sad"], a: 1 },
        { q: "Audience for a text affects:", o: ["vocabulary and tone", "publisher", "length", "none of these"], a: 0 },
        { q: "What is descriptive writing?:", o: ["tells a story", "uses vivid details", "persuades", "informs only"], a: 1 },
        { q: "Transition words connect:", o: ["sentences", "paragraphs", "ideas", "all of the above"], a: 3 },
        { q: "Persuasive writing aims:", o: ["entertain", "inform", "convince reader", "describe"], a: 2 },
        { q: "Narrative text:", o: ["explains", "tells a story", "persuades", "lists facts"], a: 1 },
        { q: "Expository writing:", o: ["persuades", "explains/informs", "entertains", "describes only"], a: 1 },
        { q: "In academic writing, avoid:", o: ["nouns", "facts", "first person too much", "verbs"], a: 2 },
        { q: "'Hook' in an essay:", o: ["summary", "grabs reader attention", "conclusion", "transition"], a: 1 },
        { q: "Thesis statement:", o: ["introduction", "main argument", "conclusion", "transition"], a: 1 },
        { q: "Body paragraphs should:", o: ["repeat thesis", "support main ideas", "conclude essay", "introduce topic"], a: 1 },
        { q: "Topic sentence introduces:", o: ["essay", "conclusion", "main idea of paragraph", "author"], a: 2 },
        { q: "Conclusion should:", o: ["introduce ideas", "summarize/restate main points", "add new info", "tell story"], a: 1 },
        { q: "Active voice is preferred when:", o: ["describing", "unclear subject", "action is important", "being poetic"], a: 2 }
      ],
      9: [
        { q: "Metaphor compares:", o: ["using 'like'", "without 'like' or 'as'", "same things", "two nouns"], a: 1 },
        { q: "Personification gives:", o: ["human qualities to objects", "descriptions of people", "comparisons", "rhythm"], a: 0 },
        { q: "Pun uses:", o: ["rhyme", "double meaning of words", "rhythm", "alliteration"], a: 1 },
        { q: "Hyperbole is:", o: ["understatement", "extreme exaggeration", "comparison", "irony"], a: 1 },
        { q: "Oxymoron pairs:", o: ["different meanings", "contrasting words together", "rhyming words", "repeated sounds"], a: 1 },
        { q: "Irony means:", o: ["serious tone", "opposite of what's expected", "similarity", "exaggeration"], a: 1 },
        { q: "Onomatopoeia:", o: ["describes", "imitates sounds", "rhymes", "compares"], a: 1 },
        { q: "Alliteration repeats:", o: ["word", "ending sounds", "beginning sounds", "sentences"], a: 2 },
        { q: "Assonance repeats:", o: ["consonant sounds", "vowel sounds", "words", "sentences"], a: 1 },
        { q: "Consonance repeats:", o: ["vowel sounds", "consonant sounds", "lines", "rhymes"], a: 1 },
        { q: "Idiom means:", o: ["single word", "phrase with figurative meaning", "comparison", "description"], a: 1 },
        { q: "'Raining cats and dogs' means:", o: ["literal rain", "raining heavily", "animals falling", "weather forecast"], a: 1 },
        { q: "Paradox is:", o: ["false statement", "contradiction that may be true", "comparison", "exaggeration"], a: 1 },
        { q: "Symbolism uses:", o: ["objects to represent ideas", "direct meaning", "comparisons", "descriptions"], a: 0 },
        { q: "Foreshadowing hints:", o: ["past", "future events", "characters", "setting"], a: 1 }
      ],
      10: [
        { q: "'Raining cats and dogs' means:", o: ["literal rain", "raining heavily", "animals falling", "animal shelter"], a: 1 },
        { q: "'Piece of cake' means:", o: ["dessert", "easy", "difficult", "food"], a: 1 },
        { q: "'Break the ice' means:", o: ["damage ice", "start conversation", "stop talking", "cold weather"], a: 1 },
        { q: "'Under the weather' means:", o: ["low clouds", "feeling sick", "outside", "rainy"], a: 1 },
        { q: "'Hit the books' means:", o: ["attack", "study", "read", "strike"], a: 1 },
        { q: "'Cost an arm and a leg' means:", o: ["body parts", "very expensive", "cheap", "average price"], a: 1 },
        { q: "'Burn the midnight oil' means:", o: ["set fire", "work late", "sleep", "use candles"], a: 1 },
        { q: "'See eye to eye' means:", o: ["look at each other", "agree", "have vision", "same height"], a: 1 },
        { q: "'Spill the beans' means:", o: ["literal beans", "reveal a secret", "cook", "tell jokes"], a: 1 },
        { q: "'Call it a day' means:", o: ["name a date", "stop working", "phone someone", "calendar"], a: 1 },
        { q: "'Get cold feet' means:", o: ["freezing feet", "get nervous/back out", "wear shoes", "temperature"], a: 1 },
        { q: "'A piece of cake' is:", o: ["literal cake", "something easy", "food", "baked good"], a: 1 },
        { q: "'Take the bull by the horns' means:", o: ["rodeo", "face difficulty boldly", "animals", "horns"], a: 1 },
        { q: "'Barking up the wrong tree' means:", o: ["dogs", "pursuing wrong course", "climbing", "animals"], a: 1 },
        { q: "'Jump on the bandwagon' means:", o: ["music", "join trend", "vehicle", "celebration"], a: 1 }
      ],
      11: [
        { q: "Homophones 'not' and 'knot':", o: ["same pronunciation", "different pronunciation", "same meaning", "opposite meanings"], a: 0 },
        { q: "'Hear' vs 'here':", o: ["same word", "homophones", "homographs", "synonyms"], a: 1 },
        { q: "'Pair' and 'pear':", o: ["homographs", "homophones", "synonyms", "antonyms"], a: 1 },
        { q: "Homonym 'bat' means:", o: ["animal or sports equipment", "nothing", "single meaning", "not both"], a: 0 },
        { q: "'Homonym' vs 'homophone':", o: ["same thing", "different concepts", "no difference", "never used"], a: 1 },
        { q: "Homograph 'lead':", o: ["sounds same", "spelled same, different meaning", "rhymes", "similar"], a: 1 },
        { q: "'Stationary' vs 'stationery':", o: ["same word", "not homophones", "homophones", "synonyms"], a: 2 },
        { q: "'Brake' and 'break':", o: ["homographs", "homophones", "antonyms", "synonyms"], a: 1 },
        { q: "'Allowed' and 'aloud':", o: ["same pronunciation", "different pronunciation", "both mean same", "opposite"], a: 0 },
        { q: "'Made' and 'maid':", o: ["homographs", "homophones", "antonyms", "none"], a: 1 },
        { q: "'Whether' and 'weather':", o: ["homophones", "homographs", "antonyms", "synonyms"], a: 0 },
        { q: "'Flour' and 'flower':", o: ["homographs", "homophones", "synonyms", "antonyms"], a: 1 },
        { q: "'Sail' and 'sale':", o: ["homophones", "homographs", "synonyms", "none"], a: 0 },
        { q: "'Right', 'write', 'rite':", o: ["all different", "homophones", "homonyms", "synonyms"], a: 1 },
        { q: "'Eye' and 'I':", o: ["homographs", "homophones", "antonyms", "same spelling"], a: 1 }
      ],
      12: [
        { q: "Prepositions show:", o: ["actions", "position/direction/time", "qualities", "persons"], a: 1 },
        { q: "'In', 'on', 'at' are:", o: ["verbs", "nouns", "prepositions", "adjectives"], a: 2 },
        { q: "'Between' for:", o: ["three or more", "two items", "groups", "locations"], a: 1 },
        { q: "'Among' for:", o: ["two only", "many items", "locations", "time"], a: 1 },
        { q: "Correct: 'Different from/than':", o: ["from", "than", "both", "neither"], a: 0 },
        { q: "'Beside' vs 'besides':", o: ["same word", "beside=next, besides=also", "besides=location", "interchangeable"], a: 1 },
        { q: "Prepositions never end:", o: ["sentences", "phrases", "paragraphs", "essays"], a: 0 },
        { q: "'During/For' time:", o: ["during=specific, for=duration", "same", "opposite", "never used"], a: 0 },
        { q: "'To' vs 'too':", o: ["same", "to=preposition, too=also", "too=preposition", "both prepositions"], a: 1 },
        { q: "'Through' and 'throughout':", o: ["same", "through=via, throughout=everywhere", "throughout=single", "none"], a: 1 },
        { q: "Prepositional phrase starts with:", o: ["verb", "preposition", "noun", "adjective"], a: 1 },
        { q: "Preposition 'without' means:", o: ["with", "lacking", "inside", "around"], a: 1 },
        { q: "'Under', 'below', 'beneath':", o: ["same meaning", "position below", "similar usage", "all different"], a: 1 },
        { q: "'Before' and 'in front of':", o: ["opposite", "time vs space", "same", "never used"], a: 1 },
        { q: "'Off' and 'from' used for:", o: ["same", "off=away from", "never differ", "same meaning"], a: 1 }
      ],
      13: [
        { q: "'A' used before:", o: ["vowel sounds", "consonant sounds", "vowels only", "specific nouns"], a: 1 },
        { q: "'An' used before:", o: ["consonant sounds", "vowel sounds", "all nouns", "verbs"], a: 1 },
        { q: "'The' is:", o: ["indefinite article", "definite article", "preposition", "adjective"], a: 1 },
        { q: "'A' and 'an' are:", o: ["definite", "indefinite", "prepositions", "conjunctions"], a: 1 },
        { q: "Omit article for:", o: ["specific nouns", "uncountable nouns", "all nouns", "verbs"], a: 1 },
        { q: "Which needs 'the':", o: ["mountains", "Mount Everest", "rivers", "cities"], a: 1 },
        { q: "Correct: 'The' before:", o: ["proper nouns", "unique nouns", "plural specific nouns", "consonants"], a: 2 },
        { q: "'Some' and 'any' with:", o: ["singular nouns", "plural/uncountable", "verbs", "adjectives"], a: 1 },
        { q: "Demonstrative articles:", o: ["this, that", "a, an", "the, that", "some, any"], a: 0 },
        { q: "'This' vs 'that':", o: ["same", "this=near, that=far", "that=near", "never used"], a: 1 },
        { q: "Possessive determiners:", o: ["my, your, his", "the, a", "some, any", "and, but"], a: 0 },
        { q: "Correct: 'One/Ones':", o: ["singular/plural replacements", "articles", "prepositions", "nouns"], a: 0 },
        { q: "'Few' vs 'a few':", o: ["same", "few=almost none, a few=some", "opposite", "same meaning"], a: 1 },
        { q: "'Little' for:", o: ["small objects", "uncountable", "adjectives", "determiners"], a: 1 },
        { q: "Articles in titles:", o: ["always used", "sometimes omitted", "never used", "varies"], a: 1 }
      ],
      14: [
        { q: "Subject-verb agreement with 'The team':", o: ["is", "are", "both", "neither"], a: 0 },
        { q: "'Everyone' uses verb:", o: ["plural", "singular", "both", "neither"], a: 1 },
        { q: "Collective nouns like 'group':", o: ["always plural", "can be singular", "never used", "prepositions"], a: 1 },
        { q: "'Neither...nor' uses verb:", o: ["plural", "singular", "based on second subject", "always plural"], a: 2 },
        { q: "Compound subjects joined by 'and':", o: ["singular verb", "plural verb", "either", "no verb needed"], a: 1 },
        { q: "'Many students/teachers' uses:", o: ["singular", "plural", "depends", "no verb"], a: 1 },
        { q: "With 'There is/There are':", o: ["always singular", "matches subject number", "always plural", "no pattern"], a: 1 },
        { q: "'What' in 'What is':", o: ["plural", "singular", "depends", "both"], a: 1 },
        { q: "Inverted sentence subject:", o: ["verb first", "still must match", "no agreement", "flexible"], a: 1 },
        { q: "'Either...or' with subjects:", o: ["plural", "singular", "matches nearer subject", "always plural"], a: 2 },
        { q: "'Nouns' that look plural but are singular:", o: ["news, physics", "cats, dogs", "people, children", "others"], a: 0 },
        { q: "Measurements like '5 miles':", o: ["singular", "plural", "depends", "no verb"], a: 1 },
        { q: "'None' of the students:", o: ["singular", "plural", "both", "neither"], a: 2 },
        { q: "Agreement with 'All' of them:", o: ["singular", "plural", "matches noun", "flexible"], a: 2 },
        { q: "When subject comes after verb:", o: ["still agrees", "doesn't agree", "no rule", "rarely used"], a: 0 }
      ],
      15: [
        { q: "'He' and 'him' are:", o: ["interchangeable", "nominative/objective pronouns", "same case", "never used differently"], a: 1 },
        { q: "'Who' vs 'whom':", o: ["no difference", "who=subject, whom=object", "opposite", "same case"], a: 1 },
        { q: "Pronoun must match:", o: ["number and gender", "length", "position", "context"], a: 0 },
        { q: "Antecedent is:", o: ["pronoun", "word pronoun replaces", "verb", "adjective"], a: 1 },
        { q: "'They/them' used for:", o: ["masculine", "feminine", "any gender", "only plural"], a: 2 },
        { q: "Reflexive pronouns:", o: ["he, she, it", "myself, yourself", "me, you", "that, this"], a: 1 },
        { q: "Correct: 'Between you and ____':", o: ["me", "I", "myself", "mine"], a: 0 },
        { q: "Possessive pronouns:", o: ["me, you", "my, your", "I, you", "we, they"], a: 1 },
        { q: "'His or hers' is:", o: ["objective", "possessive", "reflexive", "relative"], a: 1 },
        { q: "Relative pronouns:", o: ["he, she, it", "who, which, that", "me, you", "this, that"], a: 1 },
        { q: "'That' vs 'which':", o: ["same", "that=restrictive, which=non-restrictive", "opposite", "interchangeable"], a: 1 },
        { q: "Indefinite pronouns:", o: ["me, him", "anyone, something", "who, which", "I, you"], a: 1 },
        { q: "Correct: 'John and ____' in subject:", o: ["me", "I", "myself", "mine"], a: 1 },
        { q: "Demonstrative pronouns:", o: ["he, she", "this, that, these, those", "my, your", "who, which"], a: 1 },
        { q: "Pronoun reference error:", o: ["clear antecedent", "unclear antecedent", "correct pronoun", "right verb"], a: 1 }
      ],
      16: [
        { q: "Adjectives modify:", o: ["verbs", "nouns", "sentences", "pronouns only"], a: 1 },
        { q: "Adverbs modify:", o: ["nouns", "verbs, adjectives, other adverbs", "articles", "prepositions"], a: 1 },
        { q: "'Slow' vs 'slowly':", o: ["adjective/adverb", "same word", "both adjectives", "both adverbs"], a: 0 },
        { q: "Comparative adjective:", o: ["more beautiful", "most beautiful", "beautiful", "beautifully"], a: 0 },
        { q: "Superlative adjective:", o: ["more fast", "fastest", "faster", "more faster"], a: 1 },
        { q: "Rules for 'ly' endings:", o: ["never used", "creates adverbs from adjectives", "adjectives", "nouns"], a: 1 },
        { q: "'Good' vs 'well':", o: ["same", "good=adjective, well=adverb", "opposite", "both adverbs"], a: 1 },
        { q: "'Bad' vs 'badly':", o: ["interchangeable", "bad=adjective, badly=adverb", "same", "both adjectives"], a: 1 },
        { q: "Order of adjectives:", o: ["random", "opinion, size, color, noun", "color, size, opinion", "no rule"], a: 1 },
        { q: "'Very' modifies:", o: ["nouns", "adjectives/adverbs", "verbs", "articles"], a: 1 },
        { q: "Adverb of frequency:", o: ["beautiful", "always, never, usually", "suddenly", "very"], a: 1 },
        { q: "Positive adjective form:", o: ["bigger", "small", "smallest", "more small"], a: 1 },
        { q: "Irregular adjectives:", o: ["follow rules", "good, bad, far", "most adjectives", "fixed"], a: 1 },
        { q: "'Very' or 'too':", o: ["same meaning", "very=somewhat, too=excessive", "opposite", "interchangeable"], a: 1 },
        { q: "Descriptive vs limiting:", o: ["both same", "descriptive adds info, limiting specifies", "opposite", "same usage"], a: 1 }
      ],
      17: [
        { q: "Complex sentence structure:", o: ["one independent clause", "dependent + independent", "only dependent", "no clauses"], a: 1 },
        { q: "Subordinating conjunction:", o: ["and, but, or", "because, although, while", "however", "therefore"], a: 1 },
        { q: "Dependent clause requires:", o: ["period", "independent clause to complete", "semicolon", "comma only"], a: 1 },
        { q: "Relative clause starts with:", o: ["verb", "who, which, that", "preposition", "conjunction"], a: 1 },
        { q: "'If...then' shows:", o: ["contrast", "cause-effect", "time", "addition"], a: 1 },
        { q: "Adverbial clause modifies:", o: ["noun", "verb/adjective/adverb", "subject", "object"], a: 1 },
        { q: "Noun clause acts as:", o: ["modifier", "noun", "verb", "adjective"], a: 1 },
        { q: "Relative clause type:", o: ["noun clause", "adjective clause", "adverbial", "independent"], a: 1 },
        { q: "'Who' in relative clause refers to:", o: ["things", "people", "animals", "verbs"], a: 1 },
        { q: "'Which' in relative clause refers to:", o: ["people", "things/ideas", "verbs", "actions"], a: 1 },
        { q: "Reduced clause omits:", o: ["preposition", "subject and verb", "object", "noun"], a: 1 },
        { q: "Participial phrase acts as:", o: ["adjective", "noun", "verb", "preposition"], a: 0 },
        { q: "Infinitive phrase function:", o: ["noun, adjective, adverb", "only verb", "preposition", "conjunction"], a: 0 },
        { q: "Gerund phrase acts as:", o: ["adjective", "noun", "verb", "adverb"], a: 1 },
        { q: "Appositive renames:", o: ["verb", "noun", "adjective", "preposition"], a: 1 }
      ],
      18: [
        { q: "Coherence means:", o: ["interesting", "connected and clear", "long", "detailed"], a: 1 },
        { q: "Transition shows:", o: ["emotion", "relationship between ideas", "description", "character"], a: 1 },
        { q: "Pronoun reference for coherence:", o: ["complicates", "provides links", "creates confusion", "adds description"], a: 1 },
        { q: "Parallel structure:", o: ["different forms", "similar grammatical forms", "long sentences", "short sentences"], a: 1 },
        { q: "Topic sentences show:", o: ["details", "main idea of paragraph", "conclusion", "transition"], a: 1 },
        { q: "Repetition for coherence:", o: ["boring", "adds emphasis/unity", "weakens", "confuses"], a: 1 },
        { q: "Transitional devices include:", o: ["adjectives", "moreover, therefore, etc.", "nouns", "verbs"], a: 1 },
        { q: "'Furthermore' signals:", o: ["contrast", "addition", "conclusion", "time"], a: 1 },
        { q: "'However' shows:", o: ["agreement", "addition", "contrast", "conclusion"], a: 2 },
        { q: "'Consequently' indicates:", o: ["time", "cause-effect", "contrast", "addition"], a: 1 },
        { q: "Paragraph unity requires:", o: ["variety", "sentences supporting one idea", "different topics", "conclusions"], a: 1 },
        { q: "Chronological order follows:", o: ["importance", "time sequence", "logic", "interest"], a: 1 },
        { q: "Spatial order describes:", o: ["time", "space/physical location", "importance", "logic"], a: 1 },
        { q: "Coherence differs from:", o: ["unity", "unity is same", "grammar", "sentence structure"], a: 0 },
        { q: "Pronouns link:", o: ["subjects", "ideas and nouns", "verbs", "adjectives"], a: 1 }
      ],
      19: [
        { q: "Thesis statement in essay:", o: ["introduction", "main argument", "body paragraph", "conclusion"], a: 1 },
        { q: "Outline purpose:", o: ["confuse", "organize ideas before writing", "decorate", "summarize"], a: 1 },
        { q: "Introduction should:", o: ["summarize", "grab attention and present thesis", "conclude", "discuss details"], a: 1 },
        { q: "Body paragraphs:", o: ["introduce topic", "support thesis with evidence", "conclude essay", "add random info"], a: 1 },
        { q: "Topic sentence of body paragraph:", o: ["restates thesis", "supports thesis with main idea", "concludes", "transitions"], a: 1 },
        { q: "Evidence in essays can be:", o: ["opinion only", "facts, examples, quotes", "feelings", "assumptions"], a: 1 },
        { q: "Conclusion should:", o: ["introduce ideas", "summarize and restate thesis", "add new arguments", "ask questions"], a: 1 },
        { q: "Transitions between paragraphs:", o: ["optional", "connect ideas/show relationships", "end essays", "start essays"], a: 1 },
        { q: "Counterargument in persuasive essay:", o: ["supports author", "acknowledges opposite view", "ends essay", "starts essay"], a: 1 },
        { q: "Refutation means:", o: ["supporting", "proving wrong", "questioning", "agreeing"], a: 1 },
        { q: "Call to action in persuasive:", o: ["description", "urges reader to act", "summary", "introduction"], a: 1 },
        { q: "Outline format typically:", o: ["sentences", "Roman numerals and letters", "lists", "paragraphs"], a: 1 },
        { q: "Brainstorming for essays:", o: ["final draft", "generating ideas", "editing", "publishing"], a: 1 },
        { q: "Revision focuses on:", o: ["spelling", "big ideas and organization", "punctuation", "commas"], a: 1 },
        { q: "Editing checks:", o: ["content", "grammar, spelling, punctuation", "ideas", "examples"], a: 1 }
      ],
      20: [
        { q: "Formal register uses:", o: ["contractions and slang", "sophisticated language and complete forms", "casual speech", "abbreviations"], a: 1 },
        { q: "Audience awareness affects:", o: ["nothing", "tone, vocabulary, content", "only vocabulary", "only tone"], a: 1 },
        { q: "First conditional:", o: ["likely future", "unlikely future", "past", "mixed"], a: 0 },
        { q: "Second conditional:", o: ["real situation", "unreal/hypothetical", "past", "future certain"], a: 1 },
        { q: "Reported speech changes:", o: ["nothing", "tense and pronouns", "only tense", "only pronouns"], a: 1 },
        { q: "Claims need:", o: ["length", "evidence and support", "elaboration only", "examples only"], a: 1 },
        { q: "Bias in writing:", o: ["always present", "can be avoided or acknowledged", "never present", "ignored"], a: 1 },
        { q: "Rhetorical devices:", o: ["only metaphors", "techniques to persuade", "only similes", "description only"], a: 1 },
        { q: "Appeals: Ethos, Pathos, Logos:", o: ["character, emotion, logic", "logic only", "emotion only", "character only"], a: 0 },
        { q: "Fallacy is:", o: ["valid argument", "invalid/faulty reasoning", "persuasion", "evidence"], a: 1 },
        { q: "Ad hominem targets:", o: ["argument", "person instead of argument", "evidence", "logic"], a: 1 },
        { q: "Straw man fallacy:", o: ["misrepresents argument", "strong argument", "valid logic", "sound reasoning"], a: 0 },
        { q: "Loaded language:", o: ["objective", "emotionally charged", "neutral", "factual"], a: 1 },
        { q: "Citation prevents:", o: ["writing", "plagiarism", "clarity", "research"], a: 1 },
        { q: "MLA/APA formats:", o: ["interchangeable", "citation and formatting styles", "same thing", "not used"], a: 1 }
      ]
    }
  },
  Mathematics: {
    levelTitles: [
      "Whole Numbers & Place Value", "Addition & Subtraction", "Multiplication & Division", "Fractions Basics",
      "Decimals", "Percentages", "Ratio & Proportion", "Geometry Fundamentals",
      "Algebra Basics", "Linear Equations", "Systems of Equations", "Quadratic Equations",
      "Functions & Graphs", "Trigonometry", "Statistics & Probability", "Exponents & Radicals",
      "Polynomials", "Factoring", "Rational Expressions", "Advanced Topics"
    ],
    questions: {
      1: [
        { q: "What is 5 + 3?", o: ["7", "8", "9", "6"], a: 1 },
        { q: "12 - 4 equals:", o: ["8", "9", "10", "7"], a: 0 },
        { q: "2 × 3 equals:", o: ["5", "6", "7", "8"], a: 1 },
        { q: "8 ÷ 2 equals:", o: ["3", "4", "5", "6"], a: 1 },
        { q: "What is the next number? 2, 4, 6, ____", o: ["7", "8", "9", "10"], a: 1 },
        { q: "3 + 2 + 1 equals:", o: ["5", "6", "7", "8"], a: 1 },
        { q: "10 - 3 equals:", o: ["6", "7", "8", "9"], a: 1 },
        { q: "5 × 2 equals:", o: ["9", "10", "11", "12"], a: 1 },
        { q: "What is the place value of 3 in 234?", o: ["3", "30", "300", "3000"], a: 1 },
        { q: "How many tens in 50?", o: ["4", "5", "6", "7"], a: 1 },
        { q: "9 + 1 equals:", o: ["9", "10", "11", "8"], a: 1 },
        { q: "15 ÷ 3 equals:", o: ["4", "5", "6", "7"], a: 1 },
        { q: "7 + 4 equals:", o: ["10", "11", "12", "9"], a: 1 },
        { q: "6 × 1 equals:", o: ["5", "6", "7", "8"], a: 1 },
        { q: "What is 100 - 25?", o: ["70", "75", "80", "85"], a: 1 }
      ],
      2: [
        { q: "25 + 15 equals:", o: ["35", "40", "45", "50"], a: 1 },
        { q: "50 - 20 equals:", o: ["25", "30", "35", "40"], a: 1 },
        { q: "Sum of 12 and 18:", o: ["28", "30", "32", "35"], a: 1 },
        { q: "45 - 15 equals:", o: ["25", "30", "35", "40"], a: 1 },
        { q: "100 + 250 equals:", o: ["300", "350", "400", "450"], a: 0 },
        { q: "500 - 200 equals:", o: ["200", "250", "300", "350"], a: 2 },
        { q: "1000 + 500 equals:", o: ["1200", "1500", "1600", "1800"], a: 1 },
        { q: "999 - 100 equals:", o: ["800", "850", "899", "900"], a: 2 },
        { q: "What is 75 + 25?", o: ["95", "100", "105", "110"], a: 1 },
        { q: "150 - 50 equals:", o: ["90", "100", "110", "120"], a: 1 },
        { q: "200 + 300 + 100 equals:", o: ["500", "600", "700", "800"], a: 0 },
        { q: "1000 - 500 equals:", o: ["400", "500", "600", "700"], a: 1 },
        { q: "Add: 45 + 55:", o: ["95", "100", "105", "110"], a: 1 },
        { q: "Subtract: 80 - 30:", o: ["40", "50", "60", "70"], a: 1 },
        { q: "What is 120 + 80?", o: ["180", "200", "220", "240"], a: 1 }
      ],
      3: [
        { q: "3 × 4 equals:", o: ["10", "12", "14", "16"], a: 1 },
        { q: "5 × 6 equals:", o: ["25", "30", "35", "40"], a: 1 },
        { q: "12 ÷ 3 equals:", o: ["3", "4", "5", "6"], a: 1 },
        { q: "20 ÷ 5 equals:", o: ["2", "3", "4", "5"], a: 2 },
        { q: "7 × 8 equals:", o: ["54", "56", "58", "60"], a: 1 },
        { q: "9 × 9 equals:", o: ["72", "81", "90", "99"], a: 1 },
        { q: "24 ÷ 6 equals:", o: ["3", "4", "5", "6"], a: 1 },
        { q: "6 × 7 equals:", o: ["35", "42", "49", "56"], a: 1 },
        { q: "48 ÷ 8 equals:", o: ["5", "6", "7", "8"], a: 1 },
        { q: "10 × 10 equals:", o: ["90", "100", "110", "120"], a: 1 },
        { q: "36 ÷ 4 equals:", o: ["7", "8", "9", "10"], a: 2 },
        { q: "2 × 11 equals:", o: ["20", "22", "24", "26"], a: 1 },
        { q: "100 ÷ 5 equals:", o: ["15", "20", "25", "30"], a: 1 },
        { q: "4 × 12 equals:", o: ["42", "48", "54", "60"], a: 1 },
        { q: "60 ÷ 10 equals:", o: ["5", "6", "7", "8"], a: 1 }
      ],
      4: [
        { q: "What is 1/2 of 8?", o: ["2", "3", "4", "5"], a: 2 },
        { q: "1/3 of 9 equals:", o: ["2", "3", "4", "5"], a: 1 },
        { q: "1/4 of 12 equals:", o: ["2", "3", "4", "5"], a: 2 },
        { q: "Simplify: 2/4:", o: ["1/4", "1/2", "1/3", "2/3"], a: 1 },
        { q: "1/2 + 1/2 equals:", o: ["1/4", "1/2", "1", "2"], a: 2 },
        { q: "1/3 + 1/3 equals:", o: ["1/3", "1/2", "2/3", "1"], a: 2 },
        { q: "1/2 - 1/4 equals:", o: ["1/4", "1/2", "1/3", "2/3"], a: 0 },
        { q: "2/3 × 3 equals:", o: ["1", "2", "3", "4"], a: 1 },
        { q: "Which is larger: 1/2 or 1/3?", o: ["1/2", "1/3", "equal", "cannot compare"], a: 0 },
        { q: "3/4 of 12 equals:", o: ["6", "9", "12", "15"], a: 1 },
        { q: "Simplify: 4/8:", o: ["1/2", "1/4", "1/3", "2/3"], a: 0 },
        { q: "1/4 + 1/4 equals:", o: ["1/8", "1/4", "1/2", "3/4"], a: 2 },
        { q: "5/6 - 1/6 equals:", o: ["1/6", "2/3", "4/6", "1"], a: 2 },
        { q: "2/5 of 10 equals:", o: ["2", "3", "4", "5"], a: 2 },
        { q: "3/5 is equal to:", o: ["0.3", "0.5", "0.6", "0.8"], a: 2 }
      ],
      5: [
        { q: "What is 0.5 as a fraction?", o: ["1/4", "1/2", "1/3", "1/5"], a: 1 },
        { q: "0.25 equals:", o: ["1/4", "1/2", "1/3", "1/5"], a: 0 },
        { q: "0.75 as a fraction:", o: ["1/4", "1/2", "3/4", "1/3"], a: 2 },
        { q: "2.5 + 1.5 equals:", o: ["3.5", "4", "4.5", "5"], a: 2 },
        { q: "5.6 - 2.1 equals:", o: ["2.5", "3.4", "3.5", "4"], a: 2 },
        { q: "0.5 × 4 equals:", o: ["1", "2", "3", "4"], a: 1 },
        { q: "1.5 × 2 equals:", o: ["2", "2.5", "3", "3.5"], a: 2 },
        { q: "3.6 ÷ 2 equals:", o: ["1.5", "1.8", "2", "2.2"], a: 1 },
        { q: "0.25 + 0.75 equals:", o: ["0.5", "0.75", "1", "1.25"], a: 2 },
        { q: "2.3 + 1.7 equals:", o: ["3.5", "4", "4.5", "5"], a: 1 },
        { q: "10.5 - 5 equals:", o: ["4.5", "5", "5.5", "6"], a: 2 },
        { q: "0.3 × 10 equals:", o: ["0.3", "3", "30", "300"], a: 1 },
        { q: "1.25 + 0.75 equals:", o: ["1.5", "2", "2.5", "3"], a: 1 },
        { q: "4.8 - 1.3 equals:", o: ["2.5", "3", "3.5", "4"], a: 2 },
        { q: "0.02 × 100 equals:", o: ["0.2", "2", "20", "200"], a: 1 }
      ],
      6: [
        { q: "What is 50% of 100?", o: ["25", "50", "75", "100"], a: 1 },
        { q: "25% of 40 equals:", o: ["5", "10", "15", "20"], a: 1 },
        { q: "10% of 150 equals:", o: ["10", "15", "20", "25"], a: 1 },
        { q: "75% of 80 equals:", o: ["40", "50", "60", "70"], a: 2 },
        { q: "What percent is 25 of 100?", o: ["20%", "25%", "30%", "35%"], a: 1 },
        { q: "50% expressed as decimal:", o: ["0.25", "0.5", "0.75", "1"], a: 1 },
        { q: "0.25 as a percentage:", o: ["25%", "50%", "75%", "100%"], a: 0 },
        { q: "If 20% of x = 10, x equals:", o: ["30", "40", "50", "60"], a: 2 },
        { q: "15% of 200 equals:", o: ["15", "20", "25", "30"], a: 3 },
        { q: "100% of 75 equals:", o: ["50", "75", "100", "125"], a: 1 },
        { q: "33% of 99 equals approximately:", o: ["20", "25", "30", "33"], a: 2 },
        { q: "What is 20% off $50?", o: ["$30", "~$40", "$45", "$50"], a: 1 },
        { q: "5% of 200 equals:", o: ["5", "10", "15", "20"], a: 1 },
        { q: "80% as a fraction:", o: ["1/5", "2/5", "3/5", "4/5"], a: 3 },
        { q: "Percent means:", o: ["per thousand", "per hundred", "per ten", "per million"], a: 1 }
      ],
      7: [
        { q: "Ratio 2:3 means:", o: ["2 to 3", "2 + 3", "2 × 3", "2 ÷ 3"], a: 0 },
        { q: "If ratio is 1:2 and first is 5, second is:", o: ["5", "10", "15", "20"], a: 1 },
        { q: "Simplify ratio 4:8:", o: ["1:1", "1:2", "2:3", "1:3"], a: 1 },
        { q: "Proportion means:", o: ["ratio only", "equal ratios", "different ratios", "part of whole"], a: 1 },
        { q: "In proportion a:b = c:d, d equals:", o: ["a×c/b", "b×c/a", "a×b/c", "a+c/b"], a: 1 },
        { q: "If 2:5 = x:15, x equals:", o: ["4", "5", "6", "8"], a: 2 },
        { q: "Distance ratio 1:50000 means:", o: ["map to real", "1 cm = 50 km", "1 unit = 50000 units", "all of above"], a: 3 },
        { q: "In recipe, 2:3:5 ratio means:", o: ["amount", "parts of ingredients", "fractions", "percentages"], a: 1 },
        { q: "Scale factor 1:2 means:", o: ["half size", "double size", "same size", "triple size"], a: 0 },
        { q: "If ratio boys:girls = 3:4, and boys = 12, girls = :", o: ["12", "16", "20", "24"], a: 1 },
        { q: "Ratio 5:10 simplified:", o: ["1:1", "1:2", "2:3", "1:3"], a: 1 },
        { q: "Rate is:", o: ["ratio of same units", "ratio of different units", "fraction", "percent"], a: 1 },
        { q: "Speed 60 km/h means:", o: ["ratio", "rate", "proportion", "scale"], a: 1 },
        { q: "In proportion, cross multiply:", o: ["always", "sometimes", "never", "when unequal"], a: 0 },
        { q: "Direct proportion means:", o: ["both increase", "one increases other decreases", "constant", "variable"], a: 0 }
      ],
      8: [
        { q: "How many sides does a triangle have?", o: ["2", "3", "4", "5"], a: 1 },
        { q: "Square has how many right angles?", o: ["2", "3", "4", "5"], a: 2 },
        { q: "Sum of triangle angles:", o: ["90°", "180°", "270°", "360°"], a: 1 },
        { q: "Perimeter is:", o: ["area inside", "distance around", "width", "height"], a: 1 },
        { q: "Area of rectangle = :", o: ["length + width", "length × width", "2(l+w)", "l+w+l+w"], a: 1 },
        { q: "Area of triangle = :", o: ["base × height", "(base × height)/2", "base + height", "2×base×height"], a: 1 },
        { q: "Circumference of circle:", o: ["πr", "2πr", "πr²", "πd"], a: 2 },
        { q: "Diameter = :", o: ["radius", "2 × radius", "circumference", "area"], a: 1 },
        { q: "Angles in quadrilateral sum:", o: ["180°", "270°", "360°", "450°"], a: 2 },
        { q: "Isosceles triangle has:", o: ["all sides equal", "two sides equal", "no equal sides", "90° angle"], a: 1 },
        { q: "Obtuse angle is:", o: ["< 90°", "> 90° < 180°", "> 180°", "= 90°"], a: 1 },
        { q: "Volume of cube = :", o: ["side²", "side³", "6×side²", "4×side²"], a: 1 },
        { q: "Pythagorean theorem: a² + b² = :", o: ["c", "c²", "c³", "2c"], a: 1 },
        { q: "Pentagon has sides:", o: ["4", "5", "6", "7"], a: 1 },
        { q: "Area of circle = :", o: ["πr", "πr²", "2πr²", "πd²"], a: 1 }
      ]
    }
  }
};

  Physics: {
    levelTitles: [
      "Motion & Forces", "Energy & Power", "Work & Machines", "Heat & Temperature", 
      "Waves & Sound", "Electricity Basics", "Circuits", "Magnetism", 
      "Light & Optics", "Modern Physics", "Atomic Structure", "Nuclear Physics", 
      "Mechanics", "Kinematics", "Dynamics", "Gravitation", 
      "Fluid Mechanics", "Thermodynamics", "Electromagnetism", "Quantum Mechanics"
    ],
    questions: {
      1: [
        { q: "Newton's first law describes:", o: ["acceleration", "inertia", "force application", "momentum"], a: 1 },
        { q: "What is velocity?", o: ["speed only", "speed with direction", "acceleration", "distance"], a: 1 },
        { q: "Acceleration means:", o: ["constant motion", "change in velocity", "speed", "distance"], a: 1 },
        { q: "Force = :", o: ["m + a", "m × a", "m / a", "m - a"], a: 1 },
        { q: "Friction opposes:", o: ["gravity", "motion", "force", "velocity"], a: 1 },
        { q: "Weight measures:", o: ["amount of matter", "gravitational force", "density", "volume"], a: 1 },
        { q: "Newton's 3rd law:", o: ["action, no reaction", "action = reaction", "opposing forces", "all of above"], a: 2 },
        { q: "Displacement is:", o: ["distance only", "distance and direction", "speed", "velocity"], a: 1 },
        { q: "Average speed = :", o: ["distance / time", "velocity / time", "time / distance", "acceleration × time"], a: 0 },
        { q: "Terminal velocity is:", o: ["highest speed", "constant maximum speed", "zero speed", "increasing speed"], a: 1 },
        { q: "Momentum = :", o: ["m + v", "m × v", "m / v", "v / m"], a: 1 },
        { q: "Impulse = :", o: ["force × distance", "force × time", "mass × acceleration", "work / time"], a: 1 },
        { q: "Centripetal force acts:", o: ["outward", "inward toward center", "tangential", "downward"], a: 1 },
        { q: "Circular motion requires:", o: ["constant speed", "changing direction", "centripetal force", "all of above"], a: 3 },
        { q: "A car turning needs:", o: ["no force", "centripetal force", "more speed", "less speed"], a: 1 }
      ],
      2: [
        { q: "Energy is ability to:", o: ["move", "do work", "accelerate", "stop"], a: 1 },
        { q: "Kinetic energy depends on:", o: ["height", "mass and velocity", "gravity", "distance"], a: 1 },
        { q: "Potential energy = :", o: ["mgh", "m × g / h", "g × h", "m / gh"], a: 0 },
        { q: "Law of conservation:", o: ["energy created", "energy destroyed", "energy transforms", "energy increases"], a: 2 },
        { q: "Power = :", o: ["work / time", "force / time", "energy / distance", "work × time"], a: 0 },
        { q: "1 Joule equals:", o: ["1 N × m", "1 Newton", "1 kg", "1 Watt"], a: 0 },
        { q: "Watt is unit of:", o: ["force", "energy", "power", "momentum"], a: 2 },
        { q: "Which is renewable:", o: ["coal", "solar", "natural gas", "nuclear"], a: 1 },
        { q: "Efficiency means:", o: ["total energy", "useful output / input", "wasted energy", "lost power"], a: 1 },
        { q: "Heat moves by:", o: ["conduction only", "convection and radiation", "all methods", "gravity"], a: 2 },
        { q: "Mechanical energy = :", o: ["kinetic energy", "potential energy", "KE + PE", "KE - PE"], a: 2 },
        { q: "At highest point, ball has:", o: ["maximum KE", "maximum PE", "zero energy", "maximum speed"], a: 1 },
        { q: "Elastic potential energy stored in:", o: ["gravity", "springs", "heat", "friction"], a: 1 },
        { q: "Energy transformation in bulb:", o: ["none", "electrical to light", "light to heat", "no loss"], a: 1 },
        { q: "Wind energy converts:", o: ["heat to light", "kinetic to electrical", "potential to heat", "friction to motion"], a: 1 }
      ],
      3: [
        { q: "Work = :", o: ["force + distance", "force × distance × angle", "force × distance", "force / distance"], a: 2 },
        { q: "Simple machines reduce:", o: ["work done", "friction", "effort needed", "distance"], a: 2 },
        { q: "Lever is:", o: ["pulley", "simple machine with pivot", "incline", "wheel"], a: 1 },
        { q: "Mechanical advantage = :", o: ["output force / input", "input / output", "effort / load", "load / effort"], a: 3 },
        { q: "Pulley changes:", o: ["force", "direction", "work", "energy"], a: 1 },
        { q: "Inclined plane reduces:", o: ["friction", "distance", "effort needed", "height"], a: 2 },
        { q: "Wedge is:", o: ["lever", "inclined plane modified", "pulley", "wheel"], a: 1 },
        { q: "Screw is:", o: ["lever", "inclined plane", "wheel", "pulley"], a: 1 },
        { q: "Wheel and axle:", o: ["simple machine", "reduces effort", "changes direction", "all of above"], a: 3 },
        { q: "Friction in machines:", o: ["helps", "hinders", "neutral", "increases output"], a: 1 },
        { q: "Efficiency of machine:", o: ["output work / input", "always 100%", "input / output", "never achieved"], a: 0 },
        { q: "Effort force is:", o: ["force applied", "resistance", "weight", "gravity"], a: 0 },
        { q: "Load is:", o: ["effort applied", "resistance to move", "friction", "machine"], a: 1 },
        { q: "Fixed pulley:", o: ["moves with load", "redirects force", "reduces force", "both b and c"], a: 1 },
        { q: "In block and tackle:", o: ["multiple pulleys", "increase mechanical advantage", "reduce effort", "all of above"], a: 3 }
      ],
      4: [
        { q: "Temperature measures:", o: ["heat energy", "average KE of particles", "total heat", "speed of particles"], a: 1 },
        { q: "Heat flows:", o: ["random", "cold to hot", "hot to cold", "does not flow"], a: 2 },
        { q: "Thermal equilibrium:", o: ["different temps", "same temperature", "heating", "cooling"], a: 1 },
        { q: "Conduction is:", o: ["heat transfer by waves", "particle movement", "direct contact", "through fluids"], a: 2 },
        { q: "Convection happens in:", o: ["solids", "liquids and gases", "vacuum", "all media"], a: 1 },
        { q: "Radiation needs:", o: ["medium", "no medium", "contact", "movement"], a: 1 },
        { q: "Specific heat capacity:", o: ["energy per unit mass per temp", "total heat", "temperature change", "mass × temp"], a: 0 },
        { q: "Melting point of ice:", o: ["0°C", "100°C", "-10°C", "50°C"], a: 0 },
        { q: "Boiling point of water:", o: ["0°C", "50°C", "100°C", "150°C"], a: 2 },
        { q: "Thermal expansion:", o: ["decrease size", "increase size", "no change", "varies"], a: 1 },
        { q: "Latent heat:", o: ["temperature increase", "energy for phase change", "specific heat", "thermal capacity"], a: 1 },
        { q: "Insulation prevents:", o: ["conduction", "convection", "radiation", "all of above"], a: 3 },
        { q: "Good conductor of heat:", o: ["wood", "plastic", "metal", "rubber"], a: 2 },
        { q: "Absolute zero:", o: ["0°C", "-273°C", "lowest possible temp", "b and c"], a: 3 },
        { q: "First law of thermodynamics:", o: ["energy conserved", "total disorder increases", "heat flows hot→cold", "particles stop"], a: 0 }
      ],
      5: [
        { q: "Wave is:", o: ["energy transfer", "particle oscillation", "propagation of disturbance", "all of above"], a: 3 },
        { q: "Wavelength is:", o: ["wave speed", "distance between peaks", "frequency", "oscillation number"], a: 1 },
        { q: "Frequency measures:", o: ["wavelength", "oscillations per time", "speed", "amplitude"], a: 1 },
        { q: "v = f × λ relates:", o: ["speed, frequency, wavelength", "none", "only wavelength", "only speed"], a: 0 },
        { q: "Amplitude is:", o: ["wavelength", "maximum displacement", "frequency", "speed"], a: 1 },
        { q: "Transverse wave:", o: ["motion parallel to propagation", "motion perpendicular", "no motion", "circular"], a: 1 },
        { q: "Longitudinal wave:", o: ["motion parallel to propagation", "perpendicular motion", "circular", "angular"], a: 0 },
        { q: "Sound waves are:", o: ["transverse", "longitudinal", "electromagnetic", "mechanical only"], a: 1 },
        { q: "Sound speed in air:", o: ["300,000 km/s", "340 m/s", "1500 m/s", "depends on color"], a: 1 },
        { q: "Echo is:", o: ["sound absorption", "reflected sound", "sound refraction", "new sound"], a: 1 },
        { q: "Doppler effect:", o: ["frequency change", "speed change", "wavelength increase", "pitch stays same"], a: 0 },
        { q: "Interference is:", o: ["waves colliding", "superposition of waves", "sound absorption", "echo formation"], a: 1 },
        { q: "Resonance occurs when:", o: ["any frequency", "frequency matches natural", "no frequency needed", "randomly"], a: 1 },
        { q: "Diffraction is:", o: ["sound stopping", "bending around obstacles", "absorption", "reflection only"], a: 1 },
        { q: "Pitch depends on:", o: ["wavelength", "frequency", "amplitude", "speed"], a: 1 }
      ],
      6: [
        { q: "Electric charge has units:", o: ["Joules", "Coulombs", "Watts", "Volts"], a: 1 },
        { q: "Coulomb's law: F = :", o: ["kq₁q₂/r", "kq₁q₂r", "kq₁/q₂r", "k/q₁q₂r"], a: 0 },
        { q: "Electric field points:", o: ["toward negative", "away from positive", "from positive charges", "all directions"], a: 1 },
        { q: "Potential difference measured in:", o: ["Amps", "Ohms", "Volts", "Coulombs"], a: 2 },
        { q: "Current is:", o: ["charge per time", "voltage per resistance", "potential difference", "power per voltage"], a: 0 },
        { q: "Resistance depends on:", o: ["material, length, area", "current only", "voltage only", "temperature only"], a: 0 },
        { q: "Ohm's law: V = :", o: ["I/R", "I × R", "I + R", "R/I"], a: 1 },
        { q: "Conductors have:", o: ["high resistance", "low resistance", "no resistance", "variable resistance"], a: 1 },
        { q: "Insulators have:", o: ["low resistance", "high resistance", "no resistance", "zero resistance"], a: 1 },
        { q: "Conventional current flows:", o: ["electron direction", "positive to negative", "negative to positive", "randomly"], a: 1 },
        { q: "Electron flow:", o: ["positive to negative", "negative to positive", "no direction", "random"], a: 1 },
        { q: "Ammeter measures:", o: ["voltage", "current", "resistance", "power"], a: 1 },
        { q: "Voltmeter measures:", o: ["current", "voltage", "resistance", "power"], a: 1 },
        { q: "EMF means:", o: ["electric field force", "electromotive force", "electromagnetic force", "a and b"], a: 3 },
        { q: "Terminal voltage:", o: ["battery EMF", "EMF - internal voltage drop", "external voltage", "current × resistance"], a: 1 }
      ],
      7: [
        { q: "Series circuit:", o: ["parallel paths", "single path", "all in series only", "mixed connections"], a: 1 },
        { q: "In series, current:", o: ["same throughout", "different at each point", "decreases", "increases"], a: 0 },
        { q: "Total resistance in series:", o: ["R = R₁ + R₂", "R = R₁R₂/(R₁+R₂)", "R = R₁/R₂", "R = 1/R₁ + 1/R₂"], a: 0 },
        { q: "Parallel circuit:", o: ["single path", "multiple paths", "series arrangement", "no path"], a: 1 },
        { q: "In parallel, voltage:", o: ["same across each", "different", "increases", "decreases"], a: 0 },
        { q: "In parallel, current:", o: ["same", "splits at branches", "decreases", "no current"], a: 1 },
        { q: "Total resistance in parallel:", o: ["R = R₁ + R₂", "1/R = 1/R₁ + 1/R₂", "R = R₁R₂", "R = √(R₁R₂)"], a: 1 },
        { q: "Kirchhoff's voltage law:", o: ["current sum = 0", "voltage sum around loop = 0", "resistance sum = 0", "current sum = voltage"], a: 1 },
        { q: "Kirchhoff's current law:", o: ["voltage sum = 0", "current into = current out", "resistance constant", "power constant"], a: 1 },
        { q: "Fuse protects by:", o: ["increasing current", "melting at high current", "reducing voltage", "increasing voltage"], a: 1 },
        { q: "Circuit breaker:", o: ["melts", "trips when overloaded", "increases current", "decreases voltage"], a: 1 },
        { q: "Power in circuit:", o: ["V × I", "I²R", "V²/R", "all of above"], a: 3 },
        { q: "Joule heating depends on:", o: ["current", "resistance", "time", "all of above"], a: 3 },
        { q: "Short circuit:", o: ["high resistance", "zero resistance", "very low resistance", "b and c"], a: 3 },
        { q: "Capacitor stores:", o: ["current", "charge/energy", "voltage only", "power"], a: 1 }
      ]
    }
  },
  Chemistry: {
    levelTitles: [
      "Matter & Properties", "Elements & Periodic Table", "Atoms & Molecules", "Bonding",
      "Chemical Equations", "Stoichiometry", "Acids & Bases", "Reactions",
      "Oxidation-Reduction", "Energy & Reactions", "Solutions", "Gas Laws",
      "Solids & Liquids", "Organic Chemistry", "Nuclear Chemistry", "Electrochemistry",
      "Kinetics", "Equilibrium", "Complex Compounds", "Advanced Topics"
    ],
    questions: {
      1: [
        { q: "Matter has three states:", o: ["solid, liquid, crystal", "solid, liquid, gas", "wet, dry, cold", "hot, warm, cold"], a: 1 },
        { q: "Density = :", o: ["mass + volume", "mass / volume", "volume / mass", "mass × volume"], a: 1 },
        { q: "Physical change:", o: ["new substance formed", "state change, no new substance", "burning", "rusting"], a: 1 },
        { q: "Chemical change produces:", o: ["same substance", "new substance", "mass increase", "melting"], a: 1 },
        { q: "Melting point of water:", o: ["0 K", "0°C", "32 F", "all of above"], a: 3 },
        { q: "Boiling point of water:", o: ["100°C", "100 K", "212 F", "a and c"], a: 3 },
        { q: "Sublimation is:", o: ["solid to liquid", "liquid to gas", "solid to gas", "gas to solid"], a: 2 },
        { q: "Deposition is:", o: ["solid to liquid", "gas to liquid", "gas to solid", "liquid to solid"], a: 2 },
        { q: "Element contains:", o: ["one atom", "one type of atom", "molecules", "ions"], a: 1 },
        { q: "Compound contains:", o: ["one element", "two or more elements bonded", "same atoms", "ions only"], a: 1 },
        { q: "Mixture means:", o: ["chemically bonded", "physically combined", "one substance", "atoms only"], a: 1 },
        { q: "Pure substance has:", o: ["variable composition", "definite composition", "mixed elements", "changing properties"], a: 1 },
        { q: "Homogeneous mixture:", o: ["uniform throughout", "separate parts visible", "layered", "settling occurs"], a: 0 },
        { q: "Heterogeneous mixture:", o: ["uniform", "non-uniform, distinct parts", "solution", "no separation"], a: 1 },
        { q: "Colloid is:", o: ["solution", "suspension", "particles intermediate size", "true solution"], a: 2 }
      ],
      2: [
        { q: "Periodic table organized by:", o: ["mass only", "atomic number", "electrons", "properties"], a: 1 },
        { q: "Metals in periodic table:", o: ["left side", "right side", "middle", "scattered"], a: 0 },
        { q: "Nonmetals are:", o: ["left side", "right side", "middle", "all sides"], a: 1 },
        { q: "Halogens are group:", o: ["1", "17", "13", "2"], a: 1 },
        { q: "Noble gases are group:", o: ["1", "17", "18", "13"], a: 2 },
        { q: "Alkali metals are group:", o: ["1", "2", "17", "13"], a: 0 },
        { q: "Alkaline earth metals:", o: ["group 1", "group 2", "group 13", "group 17"], a: 1 },
        { q: "Transition metals:", o: ["groups 3-12", "main groups", "noble gases", "halogens"], a: 0 },
        { q: "Atomic mass unit amu:", o: ["electron mass", "proton mass", "1/12 carbon-12", "neutron mass"], a: 2 },
        { q: "Atomic number equals:", o: ["neutrons", "electrons", "protons", "nucleons"], a: 2 },
        { q: "Mass number equals:", o: ["protons only", "electrons only", "protons + neutrons", "neutrons - electrons"], a: 2 },
        { q: "Isotopes have same:", o: ["neutrons", "protons", "mass number", "electrons"], a: 1 },
        { q: "Allotropes are:", o: ["different elements", "different forms of same element", "ions", "isotopes"], a: 1 },
        { q: "Electronegativity increases:", o: ["down and left", "up and right", "horizontally", "in middle"], a: 1 },
        { q: "Ionization energy:", o: ["energy released gaining electron", "energy to remove electron", "electron affinity", "atomic mass"], a: 1 }
      ],
      3: [
        { q: "Atom contains:", o: ["nucleus only", "electrons in nucleus", "nucleus and electrons", "nucleus and neutrons"], a: 2 },
        { q: "Nucleus contains:", o: ["electrons", "protons and neutrons", "electrons and protons", "neutrons only"], a: 1 },
        { q: "Electron charge:", o: ["positive", "negative", "neutral", "varies"], a: 1 },
        { q: "Proton charge:", o: ["negative", "positive", "neutral", "varies"], a: 1 },
        { q: "Neutron charge:", o: ["positive", "negative", "neutral", "varies"], a: 2 },
        { q: "Bohr model shows:", o: ["electrons in nucleus", "electrons in orbital shells", "nucleus outside", "random electrons"], a: 1 },
        { q: "Quantum mechanics describes:", o: ["certain electron positions", "probability of electron location", "electron orbits", "nuclear structure"], a: 1 },
        { q: "Orbital is:", o: ["circular path", "region of probability", "electron orbit", "fixed shell"], a: 1 },
        { q: "Electron configuration for Carbon:", o: ["1s² 2s² 2p²", "1s² 2s¹ 2p³", "1s¹ 2s² 2p³", "1s² 2p⁴"], a: 0 },
        { q: "Valence electrons:", o: ["inner electrons", "outermost shell electrons", "nuclear electrons", "all electrons"], a: 1 },
        { q: "Noble gas configuration:", o: ["unstable", "stable, full outer shell", "reactive", "half-filled"], a: 1 },
        { q: "Cation is:", o: ["negatively charged", "positively charged", "neutral", "molecule"], a: 1 },
        { q: "Anion is:", o: ["positively charged", "negatively charged", "neutral", "atom"], a: 1 },
        { q: "Ionization removes:", o: ["neutrons", "electrons", "protons", "nucleus"], a: 1 },
        { q: "Electron affinity is:", o: ["energy to remove electron", "energy from gaining electron", "nuclear attraction", "atomic size"], a: 1 }
      ],
      4: [
        { q: "Covalent bond:", o: ["electron transfer", "electron sharing", "electrostatic attraction", "no sharing"], a: 1 },
        { q: "Ionic bond:", o: ["electron sharing", "electron transfer", "van der Waals", "hydrogen bond"], a: 1 },
        { q: "Polar covalent bond:", o: ["equal sharing", "unequal sharing", "no sharing", "electron transfer"], a: 1 },
        { q: "Nonpolar covalent bond:", o: ["equal sharing", "unequal sharing", "electron transfer", "no bonds"], a: 0 },
        { q: "Electronegativity difference > 1.7 indicates:", o: ["covalent", "polar covalent", "ionic", "none"], a: 2 },
        { q: "Hydrogen bond involves:", o: ["two hydrogens", "H with N, O, or F", "H with C", "all bonds"], a: 1 },
        { q: "Lewis structure shows:", o: ["atoms only", "valence electrons", "nuclei", "ions"], a: 1 },
        { q: "Single bond:", o: ["4 electrons shared", "6 electrons shared", "2 electrons shared", "8 electrons"], a: 2 },
        { q: "Double bond:", o: ["2 electrons", "4 electrons", "6 electrons", "8 electrons"], a: 1 },
        { q: "Triple bond:", o: ["2 electrons", "4 electrons", "6 electrons", "8 electrons"], a: 2 },
        { q: "Dative bond:", o: ["equal sharing", "both electrons from one atom", "unequal sharing", "no sharing"], a: 1 },
        { q: "Resonance occurs when:", o: ["multiple bonding structures possible", "one structure", "no bonding", "unstable"], a: 0 },
        { q: "Hybridization involves:", o: ["mixing of atomic orbitals", "bond breaking", "electron transfer", "none"], a: 0 },
        { q: "sp³ hybridization gives:", o: ["linear", "trigonal", "tetrahedral", "planar"], a: 2 },
        { q: "VSEPR theory predicts:", o: ["electron position", "molecular geometry", "bond strength", "reactivity"], a: 1 }
      ]
    }
  },
  Biology: {
    levelTitles: [
      "Cell Basics", "Cell Structures", "Cell Division", "Photosynthesis",
      "Respiration", "Enzyme Function", "DNA & Genetics", "Protein Synthesis",
      "Genetics & Heredity", "Evolution", "Ecology & Populations", "Communities",
      "Diversity", "Human Systems", "Plant Systems", "Behavior",
      "Immunity", "Reproduction", "Development", "Biotechnology"
    ],
    questions: {
      1: [
        { q: "What is the basic unit of life?", o: ["tissue", "cell", "organ", "atom"], a: 1 },
        { q: "Prokaryotic cells lack:", o: ["cell membrane", "nucleus", "cytoplasm", "ribosomes"], a: 1 },
        { q: "Eukaryotic cells have:", o: ["no nucleus", "nucleus and organelles", "no mitochondria", "no ribosomes"], a: 1 },
        { q: "Cell membrane function:", o: ["protein synthesis", "controls what enters/exits", "DNA storage", "energy production"], a: 1 },
        { q: "Cytoplasm is:", o: ["nucleus", "fluid inside cell", "cell wall", "organelle"], a: 1 },
        { q: "Nucleus contains:", o: ["ribosomes", "mitochondria", "DNA", "chloroplasts"], a: 2 },
        { q: "Mitochondria produce:", o: ["proteins", "glucose", "ATP energy", "lipids"], a: 2 },
        { q: "Chloroplasts are found in:", o: ["animal cells", "plant cells", "bacteria", "fungi"], a: 1 },
        { q: "Ribosomes synthesize:", o: ["lipids", "carbohydrates", "proteins", "nucleic acids"], a: 2 },
        { q: "Endoplasmic reticulum with ribosomes:", o: ["smooth ER", "rough ER", "neither", "both"], a: 1 },
        { q: "Golgi apparatus modifies and packages:", o: ["proteins", "lipids", "both", "nucleic acids"], a: 2 },
        { q: "Lysosome contains:", o: ["enzymes", "DNA", "proteins", "carbohydrates"], a: 0 },
        { q: "Vacuole in plant cells:", o: ["small", "large, stores water", "none", "in nucleus"], a: 1 },
        { q: "Centrioles involved in:", o: ["protein synthesis", "photosynthesis", "cell division", "none"], a: 2 },
        { q: "Prokaryotes include:", o: ["plants", "animals", "bacteria", "fungi"], a: 2 }
      ],
      2: [
        { q: "Which organelle has double membrane?", o: ["ribosome", "mitochondrion", "lysosome", "none"], a: 1 },
        { q: "Thylakoids found in:", o: ["mitochondria", "ribosomes", "chloroplasts", "nucleus"], a: 2 },
        { q: "Cristae in mitochondria:", o: ["increase surface area", "store DNA", "produce chlorophyll", "none"], a: 0 },
        { q: "Stroma is:", o: ["thylakoid stack", "mitochondrial matrix", "chloroplast fluid", "nucleus content"], a: 2 },
        { q: "Grana are:", o: ["stacks of thylakoids", "mitochondrial membranes", "ribosomal subunits", "none"], a: 0 },
        { q: "Smooth ER functions in:", o: ["protein synthesis", "lipid synthesis", "ribosome production", "DNA replication"], a: 1 },
        { q: "Cell wall provides:", o: ["flexibility", "structural support", "protein synthesis", "energy"], a: 1 },
        { q: "Cellulose in cell wall:", o: ["protein", "lipid", "carbohydrate", "nucleic acid"], a: 2 },
        { q: "Plasmodesmata:", o: ["plant cell walls only", "connections between plant cells", "animal cell junctions", "none"], a: 1 },
        { q: "Tight junctions:", o: ["plant cells only", "animal cells only", "both", "neither"], a: 1 },
        { q: "Gap junctions allow:", o: ["structural support", "communication between cells", "protection", "none"], a: 1 },
        { q: "Cilium function:", o: ["propulsion", "photosynthesis", "storage", "digestion"], a: 0 },
        { q: "Flagellum is:", o: ["short cilia", "long tail for movement", "cell wall", "none"], a: 1 },
        { q: "Microfilaments made of:", o: ["tubulin", "actin", "collagen", "keratin"], a: 1 },
        { q: "Microtubules made of:", o: ["actin", "tubulin", "myosin", "keratin"], a: 1 }
      ],
      3: [
        { q: "Mitosis produces:", o: ["gametes", "identical daughter cells", "spores", "sex cells"], a: 1 },
        { q: "Meiosis produces:", o: ["body cells", "gametes with half chromosomes", "diploid cells", "identical cells"], a: 1 },
        { q: "Prophase is characterized by:", o: ["chromosome condensation", "spindle breakdown", "nuclear envelope reform", "cell separation"], a: 0 },
        { q: "Metaphase:", o: ["chromosomes move to poles", "chromosomes align at center", "spindle fibers attach", "none"], a: 1 },
        { q: "Anaphase involves:", o: ["chromosome condensation", "sister chromatids separating", "spindle fiber formation", "none"], a: 1 },
        { q: "Telophase:", o: ["nuclear envelope reforms", "chromosomes condense", "spindle breaks", "none"], a: 0 },
        { q: "Cytokinesis in plant cells:", o: ["cleavage furrow", "cell plate", "spindle fibers", "none"], a: 1 },
        { q: "Interphase includes:", o: ["mitosis only", "G1, S, G2", "meiosis", "none"], a: 1 },
        { q: "DNA replication occurs in:", o: ["G1", "S phase", "G2", "M phase"], a: 1 },
        { q: "Homologous chromosomes pair in:", o: ["mitosis", "meiosis I", "meiosis II", "none"], a: 1 },
        { q: "Crossing over increases:", o: ["cell number", "genetic diversity", "DNA amount", "none"], a: 1 },
        { q: "Centrosome organizes:", o: ["ribosomes", "spindle fibers", "chromosomes", "none"], a: 1 },
        { q: "Binary fission occurs in:", o: ["eukaryotes", "prokaryotes", "all cells", "none"], a: 1 },
        { q: "Budding produces:", o: ["identical cells", "genetically different cells", "spores", "none"], a: 0 },
        { q: "Spore formation:", o: ["sexual reproduction", "asexual reproduction", "gamete", "none"], a: 1 }
      ],
      4: [
        { q: "Photosynthesis equation:", o: ["C6H12O6", "6CO2 + 6H2O → glucose + O2", "H2O → O2 + H", "none"], a: 1 },
        { q: "Light reactions occur in:", o: ["stroma", "thylakoids", "mitochondria", "none"], a: 1 },
        { q: "Calvin cycle occurs in:", o: ["thylakoids", "stroma", "mitochondria", "none"], a: 1 },
        { q: "Chlorophyll absorbs:", o: ["all wavelengths", "red and blue light", "green light", "none"], a: 1 },
        { q: "ATP produced in:", o: ["Calvin cycle", "light reactions", "mitochondria", "none"], a: 1 },
        { q: "NADPH produced in:", o: ["Calvin cycle", "light reactions", "Krebs cycle", "none"], a: 1 },
        { q: "Photosystem II:", o: ["releases O2", "absorbs light", "produces ATP", "all"], a: 3 },
        { q: "Photosystem I:", o: ["reduces CO2", "reduces NADP+", "absorbs light", "b and c"], a: 3 },
        { q: "Stroma reactions synthesize:", o: ["ATP", "glucose", "O2", "none"], a: 1 },
        { q: "RuBP combines with:", o: ["glucose", "ATP", "CO2", "NADPH"], a: 2 },
        { q: "Photolysis of water:", o: ["stores energy", "releases O2", "produces ATP", "all"], a: 3 },
        { q: "C3 plants fix CO2:", o: ["at night", "during day", "always", "never"], a: 1 },
        { q: "C4 plants advantage:", o: ["more O2", "less water loss", "more CO2", "none"], a: 1 },
        { q: "CAM plants:", o: ["open stomata at night", "close stomata during day", "reduce water loss", "all"], a: 3 },
        { q: "Antenna pigments:", o: ["absorb energy", "transfer energy", "release O2", "none"], a: 1 }
      ]
    }
  },
  Science: {
    levelTitles: [
      "Scientific Method", "Measurement", "Observations", "Data Collection",
      "Variables", "Hypothesis", "Experiments", "Analysis",
      "Models", "Theories", "Laws", "Earth Science",
      "Ecosystems", "Biodiversity", "Energy Cycles", "Conservation",
      "Climate", "Weather", "Resources", "Sustainability"
    ],
    questions: {
      1: [
        { q: "Scientific method begins with:", o: ["experiment", "hypothesis", "observation", "conclusion"], a: 2 },
        { q: "Hypothesis is:", o: ["proven fact", "testable prediction", "law of nature", "none"], a: 1 },
        { q: "Variable that is changed:", o: ["dependent", "independent", "control", "none"], a: 1 },
        { q: "Variable that is measured:", o: ["independent", "dependent", "controlled", "none"], a: 1 },
        { q: "Control group:", o: ["tested group", "untested group", "all groups", "none"], a: 1 },
        { q: "Experiment tests:", o: ["observations", "hypothesis", "facts", "none"], a: 1 },
        { q: "Data analysis:", o: ["planning", "testing", "interpreting results", "conclusion"], a: 2 },
        { q: "Conclusion states:", o: ["question", "hypothesis", "results and hypothesis relation", "none"], a: 2 },
        { q: "Theory in science:", o: ["guess", "well-tested explanation", "law", "opinion"], a: 1 },
        { q: "Law describes:", o: ["how to do things", "patterns in nature", "explanations", "none"], a: 1 },
        { q: "Qualitative data:", o: ["numbers", "descriptions", "measurements", "none"], a: 1 },
        { q: "Quantitative data:", o: ["descriptions", "numbers and measurements", "observations", "none"], a: 1 },
        { q: "Precision means:", o: ["closest to true value", "consistency", "accuracy", "none"], a: 1 },
        { q: "Accuracy means:", o: ["consistency", "closest to true value", "precision", "none"], a: 1 },
        { q: "Graph shows:", o: ["relationship between variables", "opinions", "descriptions", "none"], a: 0 }
      ],
      2: [
        { q: "SI unit for length:", o: ["foot", "meter", "inch", "yard"], a: 1 },
        { q: "SI unit for mass:", o: ["pound", "gram", "kilogram", "ounce"], a: 2 },
        { q: "SI unit for temperature:", o: ["Fahrenheit", "Celsius", "Kelvin", "none"], a: 2 },
        { q: "SI unit for time:", o: ["minute", "second", "hour", "day"], a: 1 },
        { q: "Prefix 'kilo':", o: ["1000", "0.001", "0.1", "100"], a: 0 },
        { q: "Prefix 'centi':", o: ["100", "0.01", "1000", "0.001"], a: 1 },
        { q: "Prefix 'milli':", o: ["1000", "0.01", "0.001", "100"], a: 2 },
        { q: "1 meter equals:", o: ["10 cm", "100 cm", "1000 cm", "0.1 cm"], a: 1 },
        { q: "1 kilogram equals:", o: ["10 grams", "100 grams", "1000 grams", "0.1 grams"], a: 2 },
        { q: "Significant figures:", o: ["all zeros", "certain and estimated digits", "decimal places", "none"], a: 1 },
        { q: "Scientific notation expresses:", o: ["whole numbers", "large/small numbers as powers of 10", "fractions", "none"], a: 1 },
        { q: "Density unit:", o: ["kg", "m", "kg/m³", "m²"], a: 2 },
        { q: "Volume of rectangle:", o: ["length × width", "length + width", "length × width × height", "2(lw)"], a: 2 },
        { q: "Percentage error:", o: ["no error", "|experimental - true|/true × 100", "true - experimental", "none"], a: 1 },
        { q: "Conversion factor:", o: ["true value", "ratio of equal quantities", "error", "none"], a: 1 }
      ]
    }
  },
  SocialScience: {
    levelTitles: [
      "Geography Basics", "Maps & Regions", "Population", "Cultures",
      "Government Systems", "History Methods", "Ancient Civilizations", "Medieval Period",
      "Renaissance & Reformation", "Age of Exploration", "Industrial Revolution", "Modern Era",
      "Political Systems", "Economics Basics", "Trade", "Global Issues",
      "Social Structure", "Religion & Philosophy", "Art & Literature", "Contemporary World"
    ],
    questions: {
      1: [
        { q: "Geography studies:", o: ["the earth", "maps only", "countries", "weather"], a: 0 },
        { q: "Latitude lines run:", o: ["north-south", "east-west", "diagonally", "randomly"], a: 1 },
        { q: "Equator is:", o: ["north of tropic", "0° latitude", "a meridian", "prime meridian"], a: 1 },
        { q: "Prime meridian is:", o: ["0° longitude", "Greenwich meridian", "reference line", "all"], a: 3 },
        { q: "Continents are:", o: ["7 major landmasses", "5 major landmasses", "countries", "oceans"], a: 0 },
        { q: "Which is largest continent:", o: ["Africa", "Asia", "Europe", "North America"], a: 1 },
        { q: "Biome is:", o: ["a city", "ecosystem with similar climate", "a country", "a state"], a: 1 },
        { q: "Climate differs from weather in:", o: ["no difference", "long-term patterns", "short-term", "none"], a: 1 },
        { q: "Tundra biome:", o: ["wet", "cold, little rain", "hot", "tropical"], a: 1 },
        { q: "Desert receives:", o: ["high rainfall", "low rainfall", "moderate rainfall", "seasonal rain"], a: 1 },
        { q: "Rainforest located near:", o: ["poles", "equator", "mountains", "none"], a: 1 },
        { q: "Ocean covers:", o: ["30% Earth", "50% Earth", "70% Earth", "90% Earth"], a: 2 },
        { q: "Compass direction abbreviations:", o: ["N, S, E, W", "North, South", "only N and S", "none"], a: 0 },
        { q: "Contour lines show:", o: ["temperature", "elevation", "population", "rivers"], a: 1 },
        { q: "Scale on map shows:", o: ["map size", "real distance", "direction", "none"], a: 1 }
      ],
      2: [
        { q: "Population density:", o: ["total population", "people per area", "birth rate", "death rate"], a: 1 },
        { q: "Birth rate measures:", o: ["deaths per year", "births per population", "age of population", "none"], a: 1 },
        { q: "Death rate measures:", o: ["births per year", "deaths per population", "disease cases", "none"], a: 1 },
        { q: "Migration is:", o: ["staying in place", "moving from place to place", "travel", "tourism"], a: 1 },
        { q: "Emigration means:", o: ["moving to country", "leaving country", "staying", "traveling"], a: 1 },
        { q: "Immigration means:", o: ["leaving country", "moving to country", "temporary stay", "none"], a: 1 },
        { q: "Push factor causes:", o: ["migration toward", "migration away", "staying", "exploration"], a: 1 },
        { q: "Pull factor causes:", o: ["migration away", "migration toward", "remaining", "none"], a: 1 },
        { q: "Culture includes:", o: ["language only", "beliefs, practices, customs", "food only", "buildings"], a: 1 },
        { q: "Acculturation is:", o: ["learning culture", "adopting new culture", "maintaining old culture", "none"], a: 1 },
        { q: "Assimilation means:", o: ["cultural exchange", "blending into new culture", "keeping culture", "none"], a: 1 },
        { q: "Language family:", o: ["related languages", "all languages", "dead languages", "none"], a: 0 },
        { q: "Monotheism believes in:", o: ["one god", "many gods", "no god", "spirits"], a: 0 },
        { q: "Polytheism believes in:", o: ["one god", "many gods", "no god", "ancestors"], a: 1 },
        { q: "Tradition is:", o: ["new practice", "ancient practice passed down", "modern", "none"], a: 1 }
      ]
    }
  },
  ComputerScience: {
    levelTitles: [
      "Computer Basics", "Hardware", "Software", "Binary & Bits",
      "Data Storage", "Networks", "Internet", "Programming Basics",
      "Variables & Data Types", "Algorithms", "Functions", "Loops",
      "Conditionals", "Arrays & Data Structures", "Object-Oriented Programming", "Database",
      "Cybersecurity", "Web Development", "Artificial Intelligence", "Big Data"
    ],
    questions: {
      1: [
        { q: "Computer processes data using:", o: ["neurons", "binary", "light", "magnetism"], a: 1 },
        { q: "Hardware consists of:", o: ["software", "physical components", "data", "programs"], a: 1 },
        { q: "Software is:", o: ["computer parts", "programs and operating system", "data", "networks"], a: 1 },
        { q: "CPU stands for:", o: ["Computer Personal Unit", "Central Processing Unit", "Central Program Unit", "none"], a: 1 },
        { q: "RAM is:", o: ["permanent storage", "temporary memory", "CPU", "hard drive"], a: 1 },
        { q: "Storage device:", o: ["RAM", "CPU", "hard drive", "none"], a: 2 },
        { q: "Monitor displays:", o: ["data", "visual output", "processed information", "all"], a: 3 },
        { q: "Keyboard input:", o: ["text", "numbers", "commands", "all"], a: 3 },
        { q: "Mouse device:", o: ["input device", "output device", "storage", "processor"], a: 0 },
        { q: "Operating system:", o: ["application program", "manages hardware/software", "data", "none"], a: 1 },
        { q: "Binary uses:", o: ["0 and 1", "0-9", "A-Z", "all symbols"], a: 0 },
        { q: "Byte equals:", o: ["1 bit", "8 bits", "16 bits", "32 bits"], a: 1 },
        { q: "Kilobyte:", o: ["1000 bits", "1000 bytes", "1024 bytes", "none"], a: 1 },
        { q: "Megabyte:", o: ["1000 KB", "1024 KB", "1000 bytes", "none"], a: 1 },
        { q: "Algorithm is:", o: ["computer", "set of steps to solve problem", "software", "data"], a: 1 }
      ],
      2: [
        { q: "Programming language:", o: ["binary", "instructions for computer", "natural language", "none"], a: 1 },
        { q: "Variable stores:", o: ["hardware", "data value", "program", "none"], a: 1 },
        { q: "Data type includes:", o: ["integer only", "integer, string, boolean", "programs", "none"], a: 1 },
        { q: "String is:", o: ["numbers", "text characters", "true/false", "code"], a: 1 },
        { q: "Boolean value:", o: ["text", "number", "true or false", "decimal"], a: 2 },
        { q: "Loop repeats:", o: ["once", "multiple times", "never", "randomly"], a: 1 },
        { q: "For loop:", o: ["conditional check", "fixed number of iterations", "based on condition", "none"], a: 1 },
        { q: "While loop:", o: ["fixed iterations", "continues while condition true", "runs once", "none"], a: 1 },
        { q: "If statement:", o: ["loops", "conditional execution", "storage", "none"], a: 1 },
        { q: "Function is:", o: ["variable", "reusable code block", "loop", "data"], a: 1 },
        { q: "Array stores:", o: ["single value", "list of values", "program", "none"], a: 1 },
        { q: "Index of array:", o: ["variable name", "position/location", "value", "none"], a: 1 },
        { q: "Class in OOP:", o: ["building", "template for objects", "function", "variable"], a: 1 },
        { q: "Object in OOP:", o: ["physical thing", "instance of class", "program", "none"], a: 1 },
        { q: "Inheritance in OOP:", o: ["receiving property", "class gaining properties from parent", "none", "all"], a: 1 }
      ]
    }
  }
};

/* Ensure all subjects are exported with their complete data structures */
if (typeof module !== 'undefined' && module.exports) {
  module.exports = SUBJECT_QUESTIONS;
}
